---
kind: service
apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: riyaz1223/helloworld
      ports:
        - containerPort: 80
...        
