--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    role: myrole
  name: static-web
spec: 
  selector: 
    containers: 
      - 
        image: "riyaz1223/helloworld:latest"
        imagepullpolicy: Always
        name: "helloworld container"
        ports: 
          - 
            containerPort: 80
            name: web
            protocol: TCP

