apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: helloworld container
      image: riyaz1223/helloworld:latest
      imagepullpolicy: Always
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
